<?php

/**
 * Implements hook_menu().
 */
function fonts_com_menu() {

  $items = array();

  $items['admin/config/user-interface/fontyourface/fonts_com'] = array(
    'title' => 'Fonts.com',
    'description' => 'Manage settings for Fonts.com',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_setup_form'),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/user-interface/fontyourface/fonts_com/setup'] = array(
    'title' => 'Set up',
    'description' => 'Account settings for Fonts.com',
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/user-interface/fontyourface/fonts_com/project'] = array(
    'title' => 'Project',
    'description' => 'Project settings for Fonts.com',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_project_form'),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['admin/config/user-interface/fontyourface/fonts_com/project/new'] = array(
    'title' => 'Create new project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_project_edit_form', ''),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/config/user-interface/fontyourface/fonts_com/project/edit/%'] = array(
    'title' => 'Edit project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_project_edit_form', 7),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_CALLBACK,
  );

  return $items;

} // fonts_com_menu

/**
 * Implements hook_fontyourface_info().
 */
function fonts_com_fontyourface_info() {

  return array(
    'name' => 'Fonts.com',
    'url' => 'http://webfonts.fonts.com/',
  );

  return $info;

} // fonts_com_fontyourface_info

/**
 * Implements hook_fontyourface_import().
 */
function fonts_com_fontyourface_import() {

  $batch = array(
    'operations' => array(
      array('fonts_com_import_process', array())
    ),
    'finished' => 'fonts_com_import_finished',
    'title' => t('Importing fonts from Fonts.com'),
    'init_message' => t('Import starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Import has encountered an error.'),
  );

  batch_set($batch);

} // fonts_com_import

/**
 * Processes importing fonts.
 */
function fonts_com_import_process(&$context) {

  module_load_include('inc', 'fonts_com', 'api');

  $per_page = 200;

  if (empty($context['sandbox'])) {

    $context['sandbox'] = array();
    $context['sandbox']['progress'] = 1;
    $context['sandbox']['max'] = fonts_com_get_all_fonts_count();

  } // if

  $import_fonts = fonts_com_get_all_fonts($context['sandbox']['progress'], $per_page);
  
  foreach ($import_fonts as $import_font) {
  
    $metadata = array(
      'details' => $import_font,
    );

    if (isset($import_font->project)) {
      $metadata['project_id'] = $import_font->project->ProjectKey;
    } // if

    $font = new stdClass;
    $font->name = $import_font->FontName;
    $font->url = 'http://webfonts.fonts.com/en-US/Project/ChooseFonts?ViewDetails=T&ViewFontID=' . $import_font->FontID . '&AddFontToPalette=T';
    $font->provider = 'fonts_com';
    $font->metadata = serialize($metadata);
    $font->css_family = "'" . $import_font->FontCSSName . "'";
    $font->foundry = $import_font->FontFoundryName;
    $font->tags = array();

    fontyourface_save_font($font);

  } // foreach

  $context['sandbox']['progress'] += $per_page;

  if ($context['sandbox']['progress'] < $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  } // if
  else {
    $context['finished'] = 1;
  } // else

} // fonts_com_import_process

/**
 * Completes import.
 */
function fonts_com_import_finished($success, $results, $operations) {

  fonts_com_enable_from_active_project();

} // fonts_com_import_finished

/**
 * Implements template_preprocess_page().
 */
function fonts_com_preprocess_page(&$vars) {

  if (!empty($vars['fontyourface'])) {

    $projects = array();
    $preview_fonts = array();

    foreach ($vars['fontyourface'] as $used_font) {

      if ($used_font->provider == 'fonts_com') {

        $metadata = unserialize($used_font->metadata);

        if (
          (isset($metadata['project_id'])) &&
          ($metadata['project_id'] != '')
        ) {
          $projects[$metadata['project_id']] = TRUE;
        } // if
        else {
          $preview_fonts[] = $used_font;
        } // else

      } // if

    } // foreach

    if (count($projects) > 0) {

      $base = 'http://fast.fonts.com/jsapi/';

      if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
        $base = 'https://fast.fonts.com/jsapi/';
      } // if

      foreach (array_keys($projects) as $project) {

        drupal_add_js($base . $project . '.js', array('type' => 'external'));
        $variables['scripts'] = drupal_get_js();

      } // foreach

    } // if
    
    if (count($preview_fonts) > 0) {
    
      $destination = file_build_uri('fontyourface/fonts_com/preview.css');

      $css = '';
    
      $destination_directory = dirname($destination);
    
      if (file_prepare_directory($destination_directory, FILE_CREATE_DIRECTORY)) {
        
        foreach ($preview_fonts as $font) {

          $metadata = unserialize($font->metadata);

          $font_css = '@font-face {' . "\n";
          $font_css .= "  font-family: " . $font->css_family . ";" . "\n";
          $font_css .= '  src: url("' . $metadata['details']->EOTURL . '");' . "\n";

          $combined_sources = array();

          $combined_sources[] = 'url("' . $metadata['details']->TTFURL . '") format("truetype")';
          $combined_sources[] = 'url("' . $metadata['details']->WOFFURL . '") format("woff")';

          if (preg_match('#origId=([^&]+)&#i', $metadata['details']->SVGURL, $svg_match)) {
            $combined_sources[] = 'url("' . $metadata['details']->SVGURL . '#' . $svg_match[1] . '") format("svg")';
          } // if

          $font_css .= '  src: ' . implode(', ', $combined_sources) . ';' . "\n";

          if ($font->css_style != '') {
            $font_css .= '  font-style: ' . $font->css_style . ';' . "\n";
          } // if

          if ($font->css_weight != '') {
            $font_css .= '  font-weight: ' . $font->css_weight . ';' . "\n";
          } // if

          $font_css .= '}' . "\n";

          $css .= $font_css . "\n\n";

        } // foreach

      } // if

      if ($css != '') {

        drupal_add_css($css, array('group' => CSS_THEME, 'type' => 'inline'));
        $vars['styles'] = drupal_get_css();

      } // if
    
    } // if

  } // if

} // fonts_com_preprocess_page

/**
 * Implements hook_fontyourface_preview().
 */
function fonts_com_fontyourface_preview($font, $text = NULL, $size = 18) {

  $output = '';

  if ($text == NULL) {
    $text = $font->name;
  } // if

  if ($size == 'all') {

    // Display variety of sizes.

    $sizes = array(32, 24, 18, 14, 12, 10);

    foreach ($sizes as $size) {

      $output .= '<div style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</div>';

    } // foreach

  } // if
  else {

    // Display single size.

    $output = '<span style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</span>';

  } // else

  return $output;

} // fonts_com_fontyourface_preview

/**
 * Provides account settings form.
 */
function fonts_com_setup_form($form, &$form_state) {

  drupal_add_js(drupal_get_path('module', 'fonts_com') . '/js/settings.js', array('weight' => 10));
  drupal_add_css(drupal_get_path('module', 'fonts_com') . '/css/settings.css');

  $form = array();

  $auth_collapsed = FALSE;
  $pass_collapsed = TRUE;
  $create_collapsed = TRUE;

  $form['auth'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $auth_collapsed,
    '#title' => t('Enter Fonts.com authentication key'),
    '#weight' => 1,
    'fonts_com_token' => array(
      '#type' => 'textfield',
      '#description' => t('This is available at !url', array('!url' => l('https://webfonts.fonts.com/en-US/Account/AccountInformation', 'https://webfonts.fonts.com/en-US/Account/AccountInformation'))),
      '#default_value' => variable_get('fonts_com_token', ''),
    ),
    'fonts_com_key_save' => array(
      '#type' => 'submit',
      '#value' => t('Save'),
    ),
  );

  $form['pass'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $pass_collapsed,
    '#weight' => 2,
    '#prefix' => '<div class="or">' . t('OR') . '</div>',
    '#title' => t('Enter Fonts.com account information'),
    'fonts_com_pass_email' => array(
      '#type' => 'textfield',
      '#title' => t('Email address'),
    ),
    'fonts_com_pass_pass' => array(
      '#type' => 'password',
      '#title' => t('Password'),
      '#description' => t('Warning: if you have previously used a key, it will be invalidated as a new key is created.'),
    ),
    'fonts_com_pass_save' => array(
      '#type' => 'submit',
      '#value' => t('Get Key'),
    ),
  );
  
  $form['create'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $create_collapsed,
    '#title' => t('Create new Fonts.com account'),
    '#weight' => 3,
    '#prefix' => '<div class="or">' . t('OR') . '</div>',
    'fonts_com_first_name' => array(
      '#type' => 'textfield',
      '#title' => t('First name'),
    ),
    'fonts_com_last_name' => array(
      '#type' => 'textfield',
      '#title' => t('Last name'),
    ),
    'fonts_com_email' => array(
      '#type' => 'textfield',
      '#title' => t('Email address'),
    ),
    'fonts_com_create' => array(
      '#type' => 'submit',
      '#value' => t('Create Account'),
    ),
  );

  return $form;

} // fonts_com_setup_form

/**
 * Validates account settings form.
 */
function fonts_com_setup_form_validate($form, &$form_state) {

  if ($form_state['input']['op'] == t('Create Account')) {

    if ($form_state['values']['fonts_com_email'] == '') {

      form_set_error('fonts_com_email', t('Email address required.'));

    } // if

  } // if

} // fonts_com_setup_form_validate

/**
 * Handles account settings form submit.
 */
function fonts_com_setup_form_submit($form, &$form_state) {

  module_load_include('inc', 'fonts_com', 'api');

  if ($form_state['input']['op'] == t('Save')) {

    variable_set('fonts_com_token', $form_state['values']['fonts_com_token']);
    drupal_set_message(t('Fonts.com key saved.'));

  } // if
  elseif ($form_state['input']['op'] == t('Get Key')) {

    $key = fonts_com_get_key_for_account($form_state['values']['fonts_com_pass_email'], $form_state['values']['fonts_com_pass_pass']);

    if ($key) {

      variable_set('fonts_com_token', $key);
      drupal_set_message(t('Fonts.com key saved.'));

    } // if

  } // elseif
  elseif ($form_state['input']['op'] == t('Create Account')) {

    $success = fonts_com_create_account($form_state['values']['fonts_com_email'], $form_state['values']['fonts_com_first_name'], $form_state['values']['fonts_com_last_name']);

    if ($success) {

      drupal_set_message(t('You will receive an email with your new password at the email address you entered, @email. Enter that email and password below to get your key.', array('@email' => $form_state['values']['fonts_com_email'])));

    } // if

  } // elseif

} // fonts_com_setup_form_submit

/**
 * Provides project settings form.
 */
function fonts_com_project_form($form, &$form_state) {

  module_load_include('inc', 'fonts_com', 'api');

  $form = array();
  
  $projects = fonts_com_get_projects();
  
  if (count($projects) > 0) {

    $form['project'] = array(
      '#type' => 'select',
      '#title' => t('Project'),
      '#options' => array('' => '-- Select a project --'),
      '#ajax' => array(
        'callback' => 'fonts_com_project_ajax_callback',
        'wrapper' => 'project-info',
      ),
    );

    foreach ($projects as $project) {

      $edit_link = l(t('Edit'), 'admin/config/user-interface/fontyourface/fonts_com/project/edit/' . $project->ProjectKey);
      $form['project']['#options'][$project->ProjectKey] = $project->ProjectName; // . ' ' . $edit_link;

    } // foreach

    $form['project']['#options']['*new*'] = '-- Create new project --';

    $form['edit_project'] = array(
      '#type' => 'submit',
      '#value' => t('Edit project'),
      '#attached' => array(
        'js' => array(
          drupal_get_path('module', 'fonts_com') . '/js/project.js', 
        )
      ),
    );

  } // if
  else {

    drupal_set_message('Your Fonts.com account currently contains no projects. Start by creating a new project.');
    drupal_goto('admin/config/user-interface/fontyourface/fonts_com/project/new');

  } // else
  
  $form['project_info'] = array(
    '#prefix' => '<div id="project-info">',
    '#suffix' => '</div>',
  );
  
  if (!empty($form_state['values']['project'])) {

    $form['project_info'] += fonts_com_project_info_form($form_state['values']['project']);

    // Prevents input from setting values so default values apply.
    unset($form_state['input']);

  } // if

  return $form;

} // fonts_com_project_form

/**
 * Handles AJAX callback for project change.
 */
function fonts_com_project_ajax_callback($form, $form_state) {

  return $form['project_info'];

} // fonts_com_project_ajax_callback

/**
 * Sets active project, or creates a new project.
 */
function fonts_com_project_form_submit($form, &$form_state) {
  
  if (isset($form_state['values']['project_name'])) {

    // Handles AJAX form submission, saves project info.

    fonts_com_project_edit_form_submit($form, $form_state);

  } // if
  else {

    // Handles non-AJAX for submission, redirects to project.

    $project_id = $form_state['values']['project'];
    $path_end = 'edit/' . $project_id;
    
    if ($project_id == '*new*') {
      $path_end = 'new';
    } // if

    drupal_goto('admin/config/user-interface/fontyourface/fonts_com/project/' . $path_end);

  } // else

} // fonts_com_project_form_submit

/**
 * Provides form to create or edit a project.
 */
function fonts_com_project_edit_form($form, &$form_state, $project_id) {

  $form = fonts_com_project_info_form($project_id); 

  return $form;

} // fonts_com_project_edit_form

/**
 * Returns project info form array.
 */
function fonts_com_project_info_form($project_id) {

  module_load_include('inc', 'fonts_com', 'api');

  $form = array();

  $form['project_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Project name'),
    '#size' => 50,
  );
  
  $form['active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Active'),
    '#description' => t('Font updates (enabled status, CSS selectors) affect the active project.'),
  );

  if (variable_get('fonts_com_project', '') == $project_id) {
    $form['active']['#default_value'] = 1;
  } // if
  else {
    $form['active']['#default_value'] = 0;
  } // else

  $form['domains'] = array(
    '#type' => 'fieldset',
    '#title' => 'Publish domains',
  );

  $domain_index = 0;

  if ($project_id != '') {
  
    $form['project_id'] = array(
      '#type' => 'value',
      '#value' => $project_id,
    );

    $project = fonts_com_get_project_by_id($project_id);

    if ($project) {

      $form['project_name']['#default_value'] = $project->ProjectName;

      $domains = fonts_com_get_domains_in_project($project->ProjectKey);
      
      foreach ($domains as $domain) {
      
        $form['domains']['domain[' . $domain_index . ']'] = array(
          '#type' => 'textfield',
          '#size' => 50,
          '#default_value' => $domain->DomainName,
        );

        $domain_index++;

      } // foreach

    } // if

  } // if

  // Add 3 empty fields.

  for ($i = 0; $i < 3; $i++) {

    $form['domains']['domain[' . $domain_index . ']'] = array(
      '#type' => 'textfield',
      '#size' => 50,
    );

    $domain_index++;

  } // for
  
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save project'),
  );

  return $form;

} // form_com_project_info_form

/**
 * Saves changes to project.
 */
function fonts_com_project_edit_form_submit($form, &$form_state) {

  module_load_include('inc', 'fonts_com', 'api');

  $values = $form_state['values'];

  if (isset($values['project_id']) && $values['project_id'] != '*new*') {

    $project = fonts_com_get_project_by_id($values['project_id']);
    $project->ProjectName = $values['project_name'];

  } // if
  else {

    $project = new StdClass;
    $project->ProjectName = $values['project_name'];

  } // else

  if ($values['active']) {

    variable_set('fonts_com_project', $values['project_id']);
    fonts_com_enable_from_active_project();

  } // if

  if (fonts_com_save_project($project)) {

    drupal_set_message(t('Project <i>@project</i> saved.', array('@project' => $project->ProjectName)));

    $new_domains = array();

    foreach ($form_state['input']['domain'] as $domain) {

      if (trim($domain) != '') {
        $new_domains[] = trim($domain);
      } // if

    } // foreach

    fonts_com_save_domains_in_project($project->ProjectKey, $new_domains);

    drupal_goto('admin/config/user-interface/fontyourface/fonts_com/project');

  } // if

} // fonts_com_project_edit_form_submit

/**
 * Implements hook_fontyourface_enable().
 */
function fonts_com_fontyourface_enable($font) {

  module_load_include('inc', 'fonts_com', 'api');

  $project = variable_get('fonts_com_project', '');
  $metadata = unserialize($font->metadata);

  if ($project == '') {

    drupal_set_message(t('Please @selectproject before enabling <i>@font</i>.', array('@selectproject' => l('select a project', 'admin/config/user-interface/fontyourface/fonts_com/project'), '@font' => $font->name)), 'error');
    return FALSE;

  } // if
  elseif (fonts_com_add_font_to_project($metadata['details']->FontID, $project)) {

    $metadata['project_id'] = $project;
    $font->metadata = serialize($metadata);
    fontyourface_save_font($font);
    return TRUE;

  } // elseif

  return FALSE;

} // fonts_com_fontyourface_enable

/**
 * Implements hook_fontyourface_disable().
 */
function fonts_com_fontyourface_disable($font) {

  module_load_include('inc', 'fonts_com', 'api');

  $project = variable_get('fonts_com_project', '');
  $metadata = unserialize($font->metadata);

  if ($project == '') {

    drupal_set_message(t('Please @selectproject before disabling <i>@font</i>.', array('@selectproject' => l('select a project', 'admin/config/user-interface/fontyourface/fonts_com/project'), '@font' => $font->name)), 'error');
    return FALSE;

  } // if
  elseif (fonts_com_delete_font_from_project($metadata['details']->FontID, $project)) {
    return TRUE;
  } // elseif

  return FALSE;

} // fonts_com_fontyourface_enable

/**
 * Enables fonts locally based on the current active project.
 */
function fonts_com_enable_from_active_project() {

  module_load_include('inc', 'fonts_com', 'api');

  // Disables all Fonts.com fonts.

  db_update('fontyourface_font')
    ->fields(array('enabled' => 0))
    ->condition('provider', 'fonts_com')
    ->execute();

  // Gets all fonts in active project.

  $urls_to_enable = array();
  $project_id = variable_get('fonts_com_project', '');
  
  if ($project_id != '') {

    $fonts = fonts_com_get_fonts_in_project($project_id);

    foreach ($fonts as $font) {

      $urls_to_enable[] = 'http://webfonts.fonts.com/en-US/Project/ChooseFonts?ViewDetails=T&ViewFontID=' . $font->FontID . '&AddFontToPalette=T';

    } // foreach

  } // if

  // Enables all fonts in active project.

  if (count($urls_to_enable) > 0) {

    db_update('fontyourface_font')
      ->fields(array('enabled' => 1))
      ->condition('provider', 'fonts_com')
      ->condition('url', $urls_to_enable, 'IN')
      ->execute();

  } // if

} // fonts_com_enable_from_active_project

/**
 * Implements hook_fontyourface_selector_update().
 */
function fonts_com_fontyourface_selector_update($font) {

  module_load_include('inc', 'fonts_com', 'api');

  $project_id = variable_get('fonts_com_project', '');
  $metadata = unserialize($font->metadata);
  $font_id = $metadata['details']->FontID;

  fonts_com_set_font_selector($project_id, $font_id, $font->css_selector);

} // fonts_com_fontyourface_selector_update

/**
 * Implements hook_fontyourface_short_preview_text().
 */
function fonts_com_fontyourface_short_preview_text($font) {

  $metadata = unserialize($font->metadata);
  
  if (strpos($metadata['details']->FontLanguage, 'Latin') === FALSE) {

    return substr($metadata['details']->FontPreviewTextLong, 0, 4);

  } // if

  return 'AaGg';

} // fonts_com_fontyourface_short_preview_text
