<?php

/**
 * Implements hook_menu().
 */
function fonts_com_menu() {

  $items = array();

  $items['admin/config/user-interface/fontyourface/fonts_com'] = array(
    'title' => 'Fonts.com',
    'description' => 'Manage settings for Fonts.com',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_setup_form'),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/user-interface/fontyourface/fonts_com/setup'] = array(
    'title' => 'Set up',
    'description' => 'Account settings for Fonts.com',
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/config/user-interface/fontyourface/fonts_com/project'] = array(
    'title' => 'Project',
    'description' => 'Account settings for Fonts.com',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fonts_com_project_form'),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;

} // fonts_com_menu

/**
 * Implements hook_fontyourface_info().
 */
function fonts_com_fontyourface_info() {

  return array(
    'name' => 'Fonts.com',
    'url' => 'http://webfonts.fonts.com/',
  );

  return $info;

} // fonts_com_fontyourface_info

/**
 * Implements hook_fontyourface_import().
 */
function fonts_com_fontyourface_import() {

  module_load_include('inc', 'fonts_com', 'api');

  $import_fonts = array();
  $projects = fonts_com_get_projects();

  foreach ($projects as $project) {

    $fonts = array();
  
    $domains = fonts_com_get_domains_in_project($project->ProjectKey);
    $domain_match = FALSE;

    foreach ($domains as $domain) {
    
      if ($domain->DomainName == $_SERVER['HTTP_HOST']) {
        $domain_match = TRUE;
      } // if
    
    } // foreach
    
    if ($domain_match) {

      $fonts = fonts_com_get_fonts_in_project($project->ProjectKey);
      
      foreach ($fonts as $font) {

        $font->project = $project;
        $import_fonts[] = $font;

      } // foreach

    } // if

  } // foreach

  foreach ($import_fonts as $import_font) {
  
    $metadata = array(
      'project_id' => $import_font->project->ProjectKey,
    );

    $font = new stdClass;
    $font->name = $import_font->FontName;
    $font->url = 'http://webfonts.fonts.com/en-US/Project/ChooseFonts?ViewDetails=T&ViewFontID=' . $import_font->FontID . '&AddFontToPalette=T';
    $font->provider = 'fonts_com';
    $font->metadata = serialize($metadata);
    $font->css_family = "'" . $import_font->FontCSSName . "'";
    $font->foundry = $import_font->FontFondryName;
    $font->tags = array();

    fontyourface_save_font($font);

  } // foreach

} // fonts_com_import

/**
 * Implements template_preprocess_page().
 */
function fonts_com_preprocess_page(&$vars) {

  if (!empty($vars['fontyourface'])) {

    $projects = array();

    foreach ($vars['fontyourface'] as $used_font) {

      if ($used_font->provider == 'fonts_com') {

        $metadata = unserialize($used_font->metadata);
        $projects[$metadata['project_id']] = TRUE;

      } // if

    } // foreach

    if (count($projects) > 0) {

      $base = 'http://fast.fonts.com/jsapi/';

      if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
        $base = 'https://fast.fonts.com/jsapi/';
      } // if

      foreach (array_keys($projects) as $project) {

        drupal_add_js($base . $project . '.js', array('type' => 'external'));
        $variables['scripts'] = drupal_get_js();

      } // foreach

    } // if

  } // if

} // fonts_com_preprocess_page

/**
 * Implements hook_fontyourface_preview().
 */
function fonts_com_fontyourface_preview($font, $text = NULL, $size = 18) {

  $output = '';

  if ($text == NULL) {
    $text = $font->name;
  } // if

  if ($size == 'all') {

    // Display variety of sizes.

    $sizes = array(32, 24, 18, 14, 12, 10);

    foreach ($sizes as $size) {

      $output .= '<div style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</div>';

    } // foreach

  } // if
  else {

    // Display single size.

    $output = '<span style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</span>';

  } // else

  return $output;

} // fonts_com_fontyourface_preview

/**
 * Provides account settings form.
 */
function fonts_com_setup_form($form, &$form_state) {

  drupal_add_js(drupal_get_path('module', 'fonts_com') . '/js/settings.js', array('weight' => 10));
  drupal_add_css(drupal_get_path('module', 'fonts_com') . '/css/settings.css');

  $form = array();

  $auth_collapsed = FALSE;
  $pass_collapsed = TRUE;
  $create_collapsed = TRUE;

  $form['auth'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $auth_collapsed,
    '#title' => t('Enter Fonts.com authentication key'),
    '#weight' => 1,
    'fonts_com_token' => array(
      '#type' => 'textfield',
      '#description' => t('This is available at !url', array('!url' => l('https://webfonts.fonts.com/en-US/Account/AccountInformation', 'https://webfonts.fonts.com/en-US/Account/AccountInformation'))),
      '#default_value' => variable_get('fonts_com_token', ''),
    ),
    'fonts_com_key_save' => array(
      '#type' => 'submit',
      '#value' => t('Save'),
    ),
  );

  $form['pass'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $pass_collapsed,
    '#weight' => 2,
    '#prefix' => '<div class="or">' . t('OR') . '</div>',
    '#title' => t('Enter Fonts.com account information'),
    'fonts_com_pass_email' => array(
      '#type' => 'textfield',
      '#title' => t('Email address'),
    ),
    'fonts_com_pass_pass' => array(
      '#type' => 'password',
      '#title' => t('Password'),
      '#description' => t('Warning: if you have previously used a key, it will be invalidated as a new key is created.'),
    ),
    'fonts_com_pass_save' => array(
      '#type' => 'submit',
      '#value' => t('Get Key'),
    ),
  );
  
  $form['create'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => $create_collapsed,
    '#title' => t('Create new Fonts.com account'),
    '#weight' => 3,
    '#prefix' => '<div class="or">' . t('OR') . '</div>',
    'fonts_com_first_name' => array(
      '#type' => 'textfield',
      '#title' => t('First name'),
    ),
    'fonts_com_last_name' => array(
      '#type' => 'textfield',
      '#title' => t('Last name'),
    ),
    'fonts_com_email' => array(
      '#type' => 'textfield',
      '#title' => t('Email address'),
    ),
    'fonts_com_create' => array(
      '#type' => 'submit',
      '#value' => t('Create Account'),
    ),
  );

  return $form;

} // fonts_com_setup_form

/**
 * Validates account settings form.
 */
function fonts_com_setup_form_validate($form, &$form_state) {

  if ($form_state['input']['op'] == t('Create Account')) {

    if ($form_state['values']['fonts_com_email'] == '') {

      form_set_error('fonts_com_email', t('Email address required.'));

    } // if

  } // if

} // fonts_com_setup_form_validate

/**
 * Handles account settings form submit.
 */
function fonts_com_setup_form_submit($form, &$form_state) {

  module_load_include('inc', 'fonts_com', 'api');

  if ($form_state['input']['op'] == t('Save')) {

    variable_set('fonts_com_token', $form_state['values']['fonts_com_token']);
    drupal_set_message(t('Fonts.com key saved.'));

  } // if
  elseif ($form_state['input']['op'] == t('Get Key')) {

    $key = fonts_com_get_key_for_account($form_state['values']['fonts_com_pass_email'], $form_state['values']['fonts_com_pass_pass']);

    if ($key) {

      variable_set('fonts_com_token', $key);
      drupal_set_message(t('Fonts.com key saved.'));

    } // if

  } // elseif
  elseif ($form_state['input']['op'] == t('Create Account')) {

    $success = fonts_com_create_account($form_state['values']['fonts_com_email'], $form_state['values']['fonts_com_first_name'], $form_state['values']['fonts_com_last_name']);

    if ($success) {

      drupal_set_message(t('You will receive an email with your new password at the email address you entered, @email. Enter that email and password below to get your key.', array('@email' => $form_state['values']['fonts_com_email'])));

    } // if

  } // elseif

} // fonts_com_setup_form_submit

/**
 * Provides project settings form.
 */
function fonts_com_project_form($form, &$form_state) {

  $form = array();

  return $form;

} // fonts_com_project_form
