<?php
// $Id$

/**
 * Implements hook_fontyourface_info().
 */
function common_fonts_fontyourface_info() {

  return array(
    'name' => 'Common Fonts',
    'url' => 'http://en.wikipedia.org/wiki/Web_typography#Web-safe_fonts',
  );

} // common_fonts_fontyourface_info

/**
 * Implements hook_fontyourface_preview().
 */
function common_fonts_fontyourface_preview($font, $text) {

  return '<span style="font-family: ' . $font->css_family . '; font-size: 24px;">' . $text . '</span>';

} // common_fonts_fontyourface_preview

/**
 * Implements hook_fontyourface_view().
 */
function common_fonts_fontyourface_view($font, $text) {

  $output = '';
  $sizes = array(32, 24, 18, 14, 12, 10);

  foreach ($sizes as $size) {

    $output .= '<div style="font-family: ' . $font->css_family . '; font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</div>';

  } // foreach

  return $output;

} // common_fonts_fontyourface_preview

/**
 * Implements hook_fontyourface_font_face().
 */
function common_fonts_fontyourface_font_face($font) {

  return FALSE;

} // common_fonts_fontyourface_font_face

/**
 * Implements hook_fontyourface_import().
 */
function common_fonts_fontyourface_import() {

  $helvetica = new stdClass;
  $helvetica->name = 'Helvetica';
  $helvetica->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $helvetica->css_family = 'Helvetica';
  $helvetica->css_style = 'normal';
  $helvetica->css_weight = 'normal';
  $helvetica->foundry = 'Adobe';
  $helvetica->license = 'Adobe Standard License Agreement';
  $helvetica->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $helvetica->tags = array('sans-serif');
  
  fontyourface_add_font($helvetica);

  $verdana = new stdClass;
  $verdana->name = 'Verdana';
  $verdana->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $verdana->css_family = 'Helvetica';
  $verdana->css_style = 'normal';
  $verdana->css_weight = 'normal';
  $verdana->foundry = 'Adobe';
  $verdana->license = 'Adobe Standard License Agreement';
  $verdana->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $verdana->tags = array('sans-serif');
  
  fontyourface_add_font($verdana);

  $arial = new stdClass;
  $arial->name = 'Verdana';
  $arial->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $arial->css_family = 'Helvetica';
  $arial->css_style = 'normal';
  $arial->css_weight = 'normal';
  $arial->foundry = 'Adobe';
  $arial->license = 'Adobe Standard License Agreement';
  $arial->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $arial->tags = array('sans-serif');
  
  fontyourface_add_font($arial);

  $times = new stdClass;
  $times->name = 'Verdana';
  $times->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $times->css_family = 'Helvetica';
  $times->css_style = 'normal';
  $times->css_weight = 'normal';
  $times->foundry = 'Adobe';
  $times->license = 'Adobe Standard License Agreement';
  $times->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $times->tags = array('serif');
  
  fontyourface_add_font($times);

  $georgia = new stdClass;
  $georgia->name = 'Verdana';
  $georgia->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $georgia->css_family = 'Helvetica';
  $georgia->css_style = 'normal';
  $georgia->css_weight = 'normal';
  $georgia->foundry = 'Adobe';
  $georgia->license = 'Adobe Standard License Agreement';
  $georgia->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $georgia->tags = array('serif');
  
  fontyourface_add_font($times);
  
  $courier = new stdClass;
  $courier->name = 'Verdana';
  $courier->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $courier->css_family = 'Helvetica';
  $courier->css_style = 'normal';
  $courier->css_weight = 'normal';
  $courier->foundry = 'Adobe';
  $courier->license = 'Adobe Standard License Agreement';
  $courier->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $courier->tags = array('monospace');
  
  fontyourface_add_font($courier);
  
  $comic_sans = new stdClass;
  $comic_sans->name = 'Verdana';
  $comic_sans->url = 'http://new.myfonts.com/fonts/adobe/helvetica/';
  $comic_sans->css_family = 'Helvetica';
  $comic_sans->css_style = 'normal';
  $comic_sans->css_weight = 'normal';
  $comic_sans->foundry = 'Adobe';
  $comic_sans->license = 'Adobe Standard License Agreement';
  $comic_sans->license_url = 'http://new.myfonts.com/viewlicense.php?lid=614';
  $comic_sans->tags = array('cursive');
  
  fontyourface_add_font($comic_sans);

} // common_fonts_fontyourface_import
