<?php

/**
 * @file
 * Removes fonts on disable.
 */

/**
 * Implements hook_enable().
 */
function typotheque_enable() {

  // Weight must be above @font-your-face weight so preprocess comes after

  db_query("UPDATE {system} SET weight = 1 WHERE name = 'typotheque'");

} // typotheque_enable

/**
 * Implements hook_disable().
 */
function typotheque_disable() {

  fontyourface_provider_disable('typotheque');
  variable_del('typotheque_key');

} // typotheque_disable
